### ISSUE TITLE
showToast() first argument: text or HTML?

### ISSUE THREAD

**Issue by jackbsteinberg** [jackbsteinberg/std-toast#12]
The developer can use the `<std-toast>` HTML element to pass in custom HTML content for the toast, but there is currently no way to do this for the `showToast()` function.

This could be solved by passing in an HTML template string as the `message` parameter of `showToast(message, options)`, for example:

```js
const toast = showToast(`<b>Hello</b> World!`);
```

Is there interest in supporting this behavior, or is the current option sufficient?

**Comment by domenic** [comment]
The issue here is security, as this would be an additional markup injection point. Libraries or tools that guard those (e.g. linters that prohibit assigning to `innerHTML`) would need to also cover the showToast() function.

**Comment by fergald** [comment]
Can we just say that the API is

```js
showToast(...).innerHTML = "..."
```

and explain that we simply don't want to add another injection point. That API is not pretty but it's not horrible.

**Comment by jackbsteinberg** [comment]
That's a good option, though I am hesitant to solidify that before I know how exactly we're using the shadow DOM and `<slot>`s, and how exactly those work with `innerHTML`
