### ISSUE TITLE
Copy or reference some std-switch FAQs

### ISSUE THREAD

**Issue by domenic** [jackbsteinberg/std-toast#22]
In the [std-switch intent to implement](https://groups.google.com/a/chromium.org/forum/#!topic/blink-dev/kP556piqDR8), some good points were raised. I tried to incorporate some of those into the std-switch explainer in https://github.com/tkent-google/std-switch/pull/17.

We should probably have similar FAQs or alternatives considered here. Maybe the simplest thing to do would be to reference those, once they get merged. Ultimately we should probably centralize these FAQs into one repository around "new HTML elements".

**Comment by domenic** [comment]
We can also link to https://github.com/whatwg/html/issues/4696 and https://github.com/whatwg/html/issues/4697

**Comment by jackbsteinberg** [comment]
Clarification added:
https://github.com/jackbsteinberg/std-toast#extra-resources
