### ISSUE TITLE
std-toast etc. look like custom element names

### ISSUE THREAD

**Issue by dominiccooney** [jackbsteinberg/std-toast#24]
Custom elements gives the part of the element namespace with hyphens in the name, with some carve-outs for legacy hyphenated names, to authors.

It would be better for compatibility if new elements did not use hyphenated names. Or is this deliberate to enable polyfills? You might want to collect evidence about whether these names are in use by authors.

**Comment by domenic** [comment]
This is deliberate. See https://github.com/tkent-google/std-switch/#why-does-the-name-have-a-dash-in-it, which #22 talks about copying or referencing :).

There isn't really a compatibility concern here, because the module import makes it opt-in!

**Comment by dominiccooney** [comment]
Iiiiinteresting. This aspect of module imports are neat. Thanks for the pointer. My $0.02, the custom elements namespace issue is deep enough in the weeds that the explainer doesn't need to be changed--if you closed this issue, I'm fine with that.

**Comment by jackbsteinberg** [comment]
Clarification added:
https://github.com/jackbsteinberg/std-toast#extra-resources
