### ISSUE TITLE
Maybe extend Notification 

### ISSUE THREAD

**Issue by GrosSacASac** [jackbsteinberg/std-toast#28]
https://developer.mozilla.org/en-US/docs/Web/API/notification

It could be extended. Add more options. CSS selectors added. This could avoid feature creep.

**Comment by domenic** [comment]
What we've found, surveying both other platforms and various design systems, is that notifications and toasts are distinct. @kenchris [summarizes this well](https://github.com/w3ctag/design-reviews/issues/385#issuecomment-502070938):

> the difference is that this is a temporary notification / infobar, like you see for PWAs ("new version available, press reload to refresh") or like in GMail ("Chat is currently unavailable") etc. These are not things you want an actual system notification for... They really depend on the surrounding content/situation unlike regular notifications

In particular, you do not want these ending up in your Android/iOS/Windows/macOS notifications tray; they are purely in-app.

We should cover this more clearly in the README.

**Comment by jackbsteinberg** [comment]
Clarification added:
https://github.com/jackbsteinberg/std-toast#extending-the-notification-api
