### ISSUE TITLE
Problem with importing

### ISSUE THREAD

**Issue by lxender** [jackbsteinberg/std-toast#38]
Hey,

I ran into a problem when trying to mess with the element. I enabled all built-in modules related flags in my Canary installation (latest version) and I can use [std-switch](https://github.com/tkent-google/std-switch) but I'm getting "Unexpected data error" when trying to import this element.

The url I'm using is taken from the readme --- `std:elements/toast`.

Additionally, it would be cool if you'd mention the flags that need to be enabled in order for this to work in the readme. My best guess was to search for "built-in" and enable them all 😄 

My enabled flags:
![chrome-flags](https://user-images.githubusercontent.com/20384895/59842756-740da580-9357-11e9-89dd-53c0f7c9a034.png)

**Comment by jackbsteinberg** [comment]
Hey @lxender,

The issue tracker here is for the standard, not specifically Chrome's implementation, so you'll need to file a bug on [crbug](www.crbug.com) for this issue. Try the next installation of Canary though, I believe some changes to the file structure were made and this behavior should work!

Thanks for engaging 😃!
